wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.39.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710471820.373957
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      3:
      - 23
      4: 3.10.13
      5: 0.15.12
      6: 4.39.0.dev0
      8:
      - 5
      13: linux-x86_64
