wandb_version: 1

data_path:
  desc: null
  value: data/COCO2017
batch_size:
  desc: null
  value: 512
num_epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 5.0e-05
weight_decay:
  desc: null
  value: 0.2
local_rank:
  desc: null
  value: 0
simplify:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710646457.499205
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      3:
      - 1
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.15.12
      6: 4.38.2
      8:
      - 5
      13: linux-x86_64
